spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/apigateway}
  main:
    allow-bean-definition-overriding: true

server:
  port: ${PORT:8080}

# Root 'app' configuration
app:
  name: api-gateway
  description: API Gateway for demo
  version: 0.0.1

  # Matches @ConfigurationProperties(prefix = "app.jwt")
  jwt:
    # This long default ensures the 32-character validation passes in the terminal
    secret: ${JWT_SECRET:dev_default_secret_key_for_api_gateway_must_be_at_least_32_chars}
    expiration: ${JWT_EXP_MS:3600000}

  # Matches @ConfigurationProperties(prefix = "app.ratelimit")
  ratelimit:
    capacity: ${RATE_LIMIT_CAPACITY:100}
    refill: ${RATE_LIMIT_REFILL:100}

logging:
  level:
    root: INFO
    com.soumyajit.apigateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: alpha
    tagsSorter: alpha